name: Deploy to AKS using Helm

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Decode kubeconfig and configure access
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t shadyemad/flask-helm-app:latest .

      - name: Push Docker image
        run: docker push shadyemad/flask-helm-app:latest

      - name: Check cluster connectivity
        run: kubectl get nodes

      - name: Deploy using Helm
        run: |
          helm upgrade --install flask-app ./flask-chart \
            --namespace shady-ns \
            --create-namespace
